let _counter = 200;
const nextId = () => `demo-${++_counter}`;

const demoStore = {
  appointments: [
    {
      _id: 'appt-1',
      customerName: 'Sarah Connor',
      customerPhone: '+230 5123 4567',
      service: 'Gel Manicure',
      appointmentDate: new Date(Date.now() + 2 * 3600000).toISOString(),
      status: 'confirmed',
      notes: '',
      price: 800,
      source: 'whatsapp',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'appt-2',
      customerName: 'John Smith',
      customerPhone: '+230 5987 6543',
      service: "Men's Haircut",
      appointmentDate: new Date(Date.now() + 5 * 3600000).toISOString(),
      status: 'confirmed',
      notes: '',
      price: 500,
      source: 'web',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      _id: 'appt-3',
      customerName: 'Emma Watson',
      customerPhone: '+230 5555 1234',
      service: 'Full Set Lashes',
      appointmentDate: new Date(Date.now() + 26 * 3600000).toISOString(),
      status: 'pending',
      notes: 'First time customer',
      price: 1200,
      source: 'whatsapp',
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ],
  services: [
    {
      _id: 'svc-1',
      name: 'Gel Manicure',
      category: 'Nails',
      price: 800,
      duration: 45,
      description: 'Long-lasting gel polish application',
      status: 'active',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'svc-2',
      name: 'Full Set Lashes',
      category: 'Lashes',
      price: 1200,
      duration: 120,
      description: 'Full eyelash extension set',
      status: 'active',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'svc-3',
      name: "Men's Haircut",
      category: 'Hair',
      price: 500,
      duration: 30,
      description: "Classic men's haircut and style",
      status: 'active',
      createdAt: new Date().toISOString(),
    },
  ],
  customers: [
    {
      _id: 'cust-1',
      name: 'Sarah Connor',
      phone: '+230 5123 4567',
      email: 'sarah@example.com',
      totalBookings: 12,
      totalSpent: 9600,
      lastVisit: new Date(Date.now() - 2 * 86400000).toISOString(),
      status: 'loyal',
      notes: '',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'cust-2',
      name: 'John Smith',
      phone: '+230 5987 6543',
      email: 'john@example.com',
      totalBookings: 3,
      totalSpent: 1500,
      lastVisit: new Date(Date.now() - 7 * 86400000).toISOString(),
      status: 'active',
      notes: '',
      createdAt: new Date().toISOString(),
    },
    {
      _id: 'cust-3',
      name: 'Emma Watson',
      phone: '+230 5555 1234',
      email: 'emma@example.com',
      totalBookings: 1,
      totalSpent: 1200,
      lastVisit: new Date(Date.now() + 86400000).toISOString(),
      status: 'new',
      notes: 'First time customer',
      createdAt: new Date().toISOString(),
    },
  ],
  conversations: [
    {
      _id: 'conv-1',
      phone: '+230 5123 4567',
      name: 'Sarah Connor',
      status: 'ai_active',
      unread: 0,
      lastMessage: 'Perfect, see you tomorrow!',
      messages: [
        { _id: 'msg-1', text: 'Hi, can I book a gel manicure for tomorrow?', sender: 'user', createdAt: new Date(Date.now() - 15 * 60000).toISOString() },
        { _id: 'msg-2', text: "Hello! I can help with that. We have these times available tomorrow:\n1. 2:00 PM\n2. 3:30 PM\n3. 4:15 PM\n\nReply with the number of your preferred time.", sender: 'bot', createdAt: new Date(Date.now() - 14 * 60000).toISOString() },
        { _id: 'msg-3', text: '2', sender: 'user', createdAt: new Date(Date.now() - 13 * 60000).toISOString() },
        { _id: 'msg-4', text: "Perfect! I've booked you in for a Gel Manicure tomorrow at 3:30 PM. You'll receive a reminder 2 hours before. See you then!", sender: 'bot', createdAt: new Date(Date.now() - 13 * 60000).toISOString() },
        { _id: 'msg-5', text: 'Perfect, see you tomorrow!', sender: 'user', createdAt: new Date(Date.now() - 12 * 60000).toISOString() },
      ],
      createdAt: new Date(Date.now() - 15 * 60000).toISOString(),
      updatedAt: new Date(Date.now() - 12 * 60000).toISOString(),
    },
    {
      _id: 'conv-2',
      phone: '+230 5987 6543',
      name: '+230 5987 6543',
      status: 'human_needed',
      unread: 2,
      lastMessage: 'Do you offer balayage?',
      messages: [
        { _id: 'msg-6', text: 'Do you offer balayage?', sender: 'user', createdAt: new Date(Date.now() - 90 * 60000).toISOString() },
        { _id: 'msg-7', text: "I'm your booking assistant. I can help you with appointments, services, and business hours. Type 'book' to get started.", sender: 'bot', createdAt: new Date(Date.now() - 89 * 60000).toISOString() },
        { _id: 'msg-8', text: 'No I specifically want to know about balayage', sender: 'user', createdAt: new Date(Date.now() - 88 * 60000).toISOString() },
      ],
      createdAt: new Date(Date.now() - 90 * 60000).toISOString(),
      updatedAt: new Date(Date.now() - 88 * 60000).toISOString(),
    },
  ],

  nextId,
};

module.exports = demoStore;
